language: node_js
sudo: required
before_install:
  - npm install -g bower polymer-cli polylint web-component-tester
before_script:
  - bower install
  - polylint --no-recursion
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - wct --local all
dist: trusty
