language: node_js
sudo: required
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install bower polymer-cli polylint web-component-tester
before_script:
  - bower install
  - polylint --no-recursion
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - wct --local all
dist: trusty
